import os
from dotenv import load_dotenv

load_dotenv()

MONGO_DETAILS = os.getenv("MONGO_URI")
SECRET_KEY = os.getenv("SECRET_KEY")
CLIENT_ID = os.getenv('CLIENT_ID')
CLIENT_SECRET = os.getenv('CLIENT_SECRET')
REDIRECT_URI = os.getenv('REDIRECT_URI')
ALGORITHM =  os.getenv('ALGORITHM')
SMTP_SERVER= os.getenv('SMTP_SERVER')
SMTP_PORT=  os.getenv('SMTP_PORT')
EMAIL_USER=  os.getenv('EMAIL_USER')
EMAIL_PASSWORD= os.getenv('EMAIL_PASSWORD')




__all__ = [MONGO_DETAILS, SECRET_KEY, CLIENT_ID, CLIENT_SECRET, REDIRECT_URI, ALGORITHM,  SMTP_SERVER, SMTP_PORT, EMAIL_USER, EMAIL_PASSWORD]

